config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    resources :galleries
  end

  resources :galleries do
    member do
      get 'download'
    end
    resources :images do
      member do
        get 'get_image'
        post 'change_public'
      end
    end
  end

  resources :images do
    resources :comments do
    end
  end

  root 'homes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    if user_signed_in?
      @image = Image.find params[:image_id]
      @comment =  @image.comments.build
    else
      redirect_to new_user_session_path
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    image = Image.find params[:image_id]
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to galleries_path, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def comment_params
    params[:comment][:user_id] = current_user.id
    params[:comment][:image_id] = params[:image_id]
    params.require(:comment).permit(:title, :body, :user_id, :image_id)
  end

end

app/views/comments/_edit_menu.html.haml
-if user_signed_in?
  -if (current_user.id == comment.user_id)
    %td= #link_to t('layout.show'), gallery_images_path(gallery), class: 'btn btn-default'
    %td= #link_to t('layout.edit', model: ''), edit_gallery_path(gallery), class: 'btn btn-default'
    %td= #link_to t('layout.destroy'), gallery, :method => :delete, :data => { :confirm => t('layout.confirm') }, class: 'btn btn-danger'
  

app/views/comments/_form.html.haml
.panel-body
  
  = form_for([@image, @comment]) do |f|
    - if @comment.errors.any?
      #error_explanation
        %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this gallery from being saved:"
        %ul
          - @comment.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.label t('layout.title') << ": "
      = f.text_field :title
    .form-group
      = f.label t('layout.body') << ": "
      = f.text_field :body
    .form-group
      = f.label t('layout.user') << ": "
      = f.label current_user.name
      .actions
        = f.submit 'Save'

app/views/comments/_index.html.haml
%h1.center-align= t('comment.index')

= link_to t('layout.new', model: 'Comment'), new_image_comment_path(params[:id]), class: 'btn btn-default'
%table.table
  %thead
    %tr
      %th= t('layout.title')
      %th= t('layout.comment')

  %tbody
    -comments.each do |comment|
      %tr
        %td= comment.title
        %td= comment.body

        =render 'comments/edit_menu', comment: comment

app/views/comments/new.html.haml
.row
  .col-lg-3
  .col-lg-6
    .panel.panel-default
      .panel-heading
        %h4= t('layouts.new', model: 'Comment')
      = render 'form'

    = link_to 'Back', :back, class: 'btn btn-default'