config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    resources :galleries
  end

  resources :galleries do
    member do
      get 'download'
    end
    resources :images do
      member do
        get 'get_image'
        post 'change_public'
      end
    end
  end

  resources :images do
    resources :comments do
    end
  end

  root 'homes#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :user
  has_many :images
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy, :download]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    if user_signed_in?
      @gallery = Gallery.new
    else
      redirect_to new_user_session_path
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery.user.email
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to galleries_path, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to galleries_path, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_path, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    input_path = @gallery.images.first.data.path.match(/(.*)\/\d+\//)[1]
    tmp_dir = "#{Rails.root}/tmp/download/#{@gallery.id}"
    tmp_file = "#{tmp_dir}/download.zip"
    FileUtils.mkdir_p(tmp_dir) unless File.directory?(tmp_dir)
    File.delete(tmp_file) if File.exist?(tmp_file)
    GalleriesHelper::ZipFileGenerator.new(input_path, tmp_file).write
    send_file tmp_file, :type=>"application/zip", :x_sendfile=>true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      begin
        @gallery = current_user.galleries.find params[:id]
      rescue
        flash[:error] = "Access denied."
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params[:gallery][:user_id] = current_user.id
      params.require(:gallery).permit(:name, :is_public, :user_id)
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
  require 'zip'

  # This is a simple example which uses rubyzip to
  # recursively generate a zip file from the contents of
  # a specified directory. The directory itself is not
  # included in the archive, rather just its contents.
  #
  # Usage:
  #   directoryToZip = "/tmp/input"
  #   outputFile = "/tmp/out.zip"
  #   zf = ZipFileGenerator.new(directoryToZip, outputFile)
  #   zf.write()
  class ZipFileGenerator
    # Initialize with the directory to zip and the location of the output archive.
    def initialize(inputDir, outputFile)
      @inputDir = inputDir
      @outputFile = outputFile
    end

    # Zip the input directory.
    def write
      entries = Dir.entries(@inputDir); entries.delete('.'); entries.delete('..')
      io = Zip::File.open(@outputFile, Zip::File::CREATE)
      writeEntries(entries, '', io)
      io.close
    end

    # A helper method to make the recursion work.

    private

    def writeEntries(entries, path, io)
      entries.each do |e|        
        zipFilePath = path == '' ? e : File.join(path, e)
        diskFilePath = File.join(@inputDir, zipFilePath)
        puts 'Deflating ' + diskFilePath
        if File.directory?(diskFilePath)
          io.mkdir(zipFilePath)
          subdir = Dir.entries(diskFilePath); subdir.delete('.'); subdir.delete('..')
          writeEntries(subdir, zipFilePath, io)
        else
          io.get_output_stream(zipFilePath) { |f| f.puts(File.open(diskFilePath, 'rb').read) }
        end
      end
    end
  end
end

app/views/galleries/_edit_menu.html.erb
<% if user_signed_in? %>
  <% if (current_user.id == gallery.user.id) %>
    <td>
      <%= link_to t('layout.show'), gallery_images_path(gallery), class: 'btn btn-default' %>
    </td>
    <td>
      <%= link_to t('layout.edit', model: ''), edit_gallery_path(gallery), class: 'btn btn-default' %>
    </td>
    <td>
      <%= link_to t('layout.destroy'), gallery, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </td>
    <td>
      <%= link_to t('layout.download'), download_gallery_path(gallery), class: 'btn btn-default' %>
    </td>
  <% elsif gallery.is_public == true %>
    <td>
      <%= link_to t('layout.show'), gallery_images_path(gallery), class: 'btn btn-default' %>
    </td>
    <td></td>
    <td></td>
  <% else %>
    <td></td>
    <td></td>
    <td></td>
  <% end %>
<% elsif gallery.is_public == true %>
  <td>
    <%= link_to t('layout.show'), gallery_images_path(gallery), class: 'btn btn-default' %>
  </td>
  <td></td>
  <td></td>
<% else %>
  <td></td>
  <td></td>
  <td></td>
<% end %>

app/views/galleries/_form.html.haml
.panel-body
  = form_for @gallery do |f|
    - if @gallery.errors.any?
      #error_explanation
        %h2= "#{pluralize(@gallery.errors.count, "error")} prohibited this gallery from being saved:"
        %ul
          - @gallery.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      = f.label t('layouts.name') << ": "
      = f.text_field :name
    .form-group
      = f.label t('layouts.public') << ": "
      = f.check_box :is_public    
      .actions
        = f.submit 'Save'

app/views/galleries/edit.html.haml
.row
  .col-lg-3
  .col-lg-6
    .panel.panel-default
      .panel-heading
        %h4= t('gallery.edit')
      = render 'form'


    = link_to t('layout.show'), @gallery, class: 'btn btn-default'
    \|
    = link_to t('layout.back'), :back, class: 'btn btn-default'
  .col-lg-3

app/views/galleries/index.html.haml
%h1.center-align= t('gallery.index')

%table.table
  %thead
    %tr
      %th= t('layout.name')
      %th= t('layout.public')
      %th= t('layout.user')
      %th= t('gallery.count')
      %th
      %th
      %th

  %tbody
    - @galleries.each do |gallery|
      %tr
        %td= gallery.name
        %td= gallery.is_public
        %td= User.find(gallery.user_id).name
        %td= gallery.images.count
        =render 'galleries/edit_menu', gallery: gallery



%br

= link_to t('layout.new', model: 'Gallerie'), new_gallery_path, class: 'btn btn-default'

app/views/galleries/new.html.haml
.row
  .col-lg-3
  .col-lg-6
    .panel.panel-default
      .panel-heading
        %h4= t('layouts.new', model: 'Gallery')
      = render 'form'

    = link_to 'Back', :back, class: 'btn btn-default'

app/views/galleries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @gallery.name
%p
  %b Is public:
  = @gallery.is_public
%p
  %b User:
  = @gallery.user_id



= link_to t("gallery.new_image"), gallery_images_path(params[:id])

= link_to t("layout.edit"), edit_gallery_path(@gallery)
\|
= link_to t("layout.back"), :back