config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    resources :galleries
  end

  resources :galleries do
    member do
      get 'download'
    end
    resources :images do
      member do
        get 'get_image'
        post 'change_public'
      end
    end
  end

  resources :images do
    resources :comments do
    end
  end

  root 'homes#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  has_many :comments

  MiniExiftool.pstore_dir = Rails.root.join('tmp').to_s

  has_attached_file :data,
    :path => ":rails_root/uploads/:attachment/:gallery_id/:id/:basename_:style.:extension",
    #:url => '/uploads/:attachment/:user_id/:basename_:style.:extension',
    :styles => {
      :preview  => ['200>',  :jpg, :quality => 70],
      :medium => ['1600>',  :jpg, :quality => 70],
      :large => ['1920>', :jpg, :quality => 70]
    }


  validates_attachment_content_type :data, :content_type => /\Aimage\/.*\Z/


  def convert_gps(gps_data)
    data = gps_data.match(/(\d+) deg (\d+)\' (\d+.\d+)/)
    data[1].to_f + (data[2].to_f / 60) + (data[3].to_f / 3600)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:edit, :update, :destroy]
  helper_method :convert_gps
  before_filter :find_gallery

  def get_image
    @image = @gallery.images.find(params[:id])
    send_file @image.data.path(params[:size]), disposition: 'inline', type: 'image/jpeg', x_sendfile: true
  end

  def convert_gps(gps_data)
    data = gps_data.match(/(\d+) deg (\d+)\' (\d+.\d+)/)
    data[1].to_f + (data[2].to_f / 60) + (data[3].to_f / 3600)
  end

  def change_public
    image = @gallery.images.find params[:id]
    if image[:is_public]
      image[:is_public] = false
    else
      image[:is_public] = true
    end

    respond_to do |format|
      if image.save
        if image[:is_public]
          format.html { redirect_to :back, notice: "You changed this image to PUBLIC"}
          format.json { render json: @image }
        else
          format.html { redirect_to :back, notice: "You changed this image to PRIVATE" }
          format.json { render json: @image }
        end
      else
        format.html { redirect_to :back, notice: 'Something went wrong! Please try it again.' }
        format.json { render json: @image }
      end
    end
  end


  # GET /images
  # GET /images.json
  def index
    @images = @gallery.images
  end

  # GET /images/1
4  # GET /images/1.json
  def show
    @image = @gallery.images.find(params[:id])
  end

  # GET /images/new
  def new
    if user_signed_in?
      if current_user.id == @gallery.user_id
        @image = @gallery.images.build
      else
        flash[:error] = "Access denied."
        redirect_to :back
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /images/1/edit
  def edit
    @image = @gallery.images.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = @gallery.images.build(image_params)
    if @image.save
      render json: { message: "success"}, :status => 200
    else
      render json: { error: @post.errors.full_messages.join(',')}, :status => 400
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @image = @gallery.images.find(params[:id])
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to gallery_images_path, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = @gallery.images.find(params[:id])
    @image.destroy
    respond_to do |format|
      format.html { redirect_to gallery_images_path, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def find_gallery
      begin
        @gallery = Gallery.find(params[:gallery_id]) if Gallery.find(params[:gallery_id]).is_public
        if @gallery.nil?
          @gallery = current_user.galleries.find params[:gallery_id]
        end
      rescue
        flash[:error] = "Access denied."
        redirect_to root_url
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      begin
        @gallery = current_user.galleries.find params[:gallery_id]
        @image = @gallery.images.find(params[:id])
      rescue
        flash[:error] = "Access denied."
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:gallery_id, :data, :is_public)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_edit_menu.html.haml
-if user_signed_in?
  -if (current_user.id == @gallery.user.id)
    = link_to t('layout.show'), gallery_image_path(id: image.id), class: 'btn btn-default'
    = link_to t('layout.edit'), edit_gallery_image_path(id: image.id), class: 'btn btn-default'
    = link_to t('layout.destroy'), [@gallery, image], :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
  -elsif @gallery.is_public == true
    = link_to t('layout.show'), gallery_image_path(id: image.id), class: 'btn btn-default'


  -else



-elsif @gallery.is_public == true
  = link_to t('layout.show'), gallery_image_path(id: image.id), class: 'btn btn-default'


-else
  = link_to t('layout.show'), gallery_image_path(id: image.id), class: 'btn btn-default'

app/views/images/_exif.html.erb
<% values = {"Type": "type", "Filesize" => "filesize", "ISO" => "iso", "Create Date": "createdate", "File Type": "filetype", "Make": "make", "Model": "model", "Color Space": "colorspace", "GPS Position": "gpsposition", "Size": "size", "Sutter Speed": "shutterspeed", "Exposure Time": "exposuretime", "F Number": "fnumber", "aperturevalue": "aperturevalue", "Ligth Source": "lightsource", "Flash": "flash", "Focallength": "focallength", "Lens Info": "lensinfo", "Software": "software" } %>

<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">
        EXIF Data
      </a>
    </li>
    <% values.each do |key, value| %>
    <li>
      <div class="left">
        <%= "#{key}" %>
      </div>
      <div class="right">
        <%= "#{image.send(value.to_s)}" %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/images/_form.html.haml
= form_for([@gallery, @image]) do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :gallery_id
    = f.number_field :gallery_id
  .field
    = f.label :data
    = f.file_field :data
  .field
    = f.label :is_public
    = f.check_box :is_public
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
.row
  .col-lg-3
  .col-lg-6
    .panel.panel-default
      .panel-heading
        %h4= t('layout.image.edit')
      = render 'form'

    = link_to t('layout.show'), gallery_image_path
    \|
    = link_to t('layout.back'), :back
  .col-lg-3

app/views/images/index.html.erb
<div class="gallery">
  <div class="div">
    <div class="btn-group">
      <button class="btn btn-info" id="gallery">PhotoSwipe</button>
      <%= link_to 'New Image', new_gallery_image_path, class: 'btn btn-success', 'data-no-turbolink' => true %>
    </div>
  </div>
  <% @images.each_slice(4).each do |group| %>
    <div class="row margin-image">
      <% group.each do |image| %>
        <div class="col-lg-3">

            <div class="col-lg-6">
              <%= link_to (image_tag get_image_gallery_image_path(@gallery, image, size: 'preview'), class: 'img-rounded img-responsive center-block'), gallery_image_path(id: image.id) %>
            </div>
            <div class="col-lg-6">
              <div class="btn-group-vertical">
                <%= render 'images/edit_menu', image: image %>
              </div>
            </div>
          
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/images/new.html.haml
= form_for([@gallery, @image], html: { multipart: true, class: "dropzone", id: "dropzone" }) do |f|
  .fallback
    = f.file_field :data
    %br/
    = f.submit t('layout.submit')
%br/

= link_to t('layout.back'), :back

app/views/images/show.html.haml
%p#notice= notice
.row
  .col-lg-3
    -image = MiniExiftool.new @image.data.path
    =render 'images/exif', image: image
  .col-lg-6
    =link_to (image_tag get_image_gallery_image_path(@gallery, @image, size: 'medium'), class: 'img-rounded img-responsive center-block'), get_image_gallery_image_path(@gallery, @image, size: 'original'), :target => "_blank"
    .margin-image
    -unless image.gpslongitude.nil? || image.gpslatitude.nil?
      = image_tag "http://maps.google.com/maps/api/staticmap?size=1200x600&sensor=false&zoom=16&markers=#{convert_gps(image.gpslatitude)}%2C#{convert_gps(image.gpslongitude)}&maptype=hybrid&style=feature:all", class: 'img-rounded img-responsive center-block'
    =render 'comments/index', comments: @image.comments
  .col-lg-3
    .btn-group-vertical
      %td= link_to t('layout.edit'), edit_gallery_image_path(@gallery, @image), class: 'btn btn-default'
      = link_to t('layout.back'), :back, class: 'btn btn-default'
      - if @image[:is_public]
        = link_to t('layout.private'), {:action => :change_public, :controller => :images}, :method => :post, class: 'btn btn-success'
      - else
        = link_to t('layout.public'), {:action => :change_public, :controller => :images}, :method => :post, class: 'btn btn-danger'