config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do
    resources :galleries
  end

  resources :galleries do
    member do
      get 'download'
    end
    resources :images do
      member do
        get 'get_image'
        post 'change_public'
      end
    end
  end

  resources :images do
    resources :comments do
    end
  end

  root 'homes#index'

end

app/views/layouts/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} alert-dismissible fade in"}
    %button.close{"data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    = message

app/views/layouts/_navigation.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/") Pixxolo
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li= link_to t('layouts.home'), root_path
        %li= link_to t('layouts.gallery'), galleries_path
      .nav.navbar-nav.navbar-right
        = render 'layouts/user_manager'

app/views/layouts/_photo_swipe.html.haml
/ Root element of PhotoSwipe. Must have class pswp.
.pswp{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  /
    Background of PhotoSwipe.
    It's a separate element, as animating opacity is faster than rgba().
  .pswp__bg
  / Slides wrapper with overflow:hidden.
  .pswp__scroll-wrap
    / Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory.
    .pswp__container
      / don't modify these 3 pswp__item elements, data is added later on
      .pswp__item
      .pswp__item
      .pswp__item
    / Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed.
    .pswp__ui.pswp__ui--hidden
      .pswp__top-bar
        / Controls are self-explanatory. Order can be changed.
        .pswp__counter
        %button.pswp__button.pswp__button--close{:title => "Close (Esc)"}
        %button.pswp__button.pswp__button--share{:title => "Share"}
        %button.pswp__button.pswp__button--fs{:title => "Toggle fullscreen"}
        %button.pswp__button.pswp__button--zoom{:title => "Zoom in/out"}
        / Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR
        / element will get class pswp__preloader--active when preloader is running
        .pswp__preloader
          .pswp__preloader__icn
            .pswp__preloader__cut
              .pswp__preloader__donut
      .pswp__share-modal.pswp__share-modal--hidden.pswp__single-tap
        .pswp__share-tooltip
      %button.pswp__button.pswp__button--arrow--left{:title => "Previous (arrow left)"}
      %button.pswp__button.pswp__button--arrow--right{:title => "Next (arrow right)"}
      .pswp__caption
        .pswp__caption__center

app/views/layouts/_user_manager.html.erb
<% if user_signed_in? %>
  <li>
    <%= render 'devise/shared/edit' %>
  </li>
  <li>
    <%= render 'devise/shared/logout' %>
  </li>
<% else %>
  <li>
    <%= render 'devise/shared/login' %>
  </li>
  <li>
    <%= link_to ('<span class="glyphicon glyphicon-user"></span> Sign up').html_safe, "#registration", "data-toggle" => "modal", "data-target" => "#registration" %>
  </li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pixxolo


    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true

    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
    = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"

    = csrf_meta_tags

  %body
    = render 'layouts/photo_swipe'
    %header
    = render 'layouts/navigation'
    .container
      .row
        = render 'devise/sessions/new'
        = render 'devise/registrations/new'
        = render 'devise/registrations/edit'
        = render partial: "layouts/flash_messages", flash: flash
        .col-lg-12
          = yield